version: '3.9'
services:
  nginx:
    image: docker.io/nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s