version: '3.9'
services:
  master:
    image: postgres:latest
    container_name: master
    restart: unless-stopped
    volumes:
      - ./config-postgres/init-master.sh:/docker-entrypoint-initdb.d/init.sh
      - .:/tmp/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=duytc
      - POSTGRES_DB=hamed
      - REP_USER=rep
      - REP_PASSWORD=123456
    ports:
      - '5432:5432'

  slave:
    image: postgres:latest
    container_name: slave
    ports:
      - '5433:5432'
    volumes:
      - ./config-postgres/init-slave.sh:/docker-entrypoint-initdb.d/init.sh
      - .:/tmp/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=duytc
      - POSTGRES_DB=hamed
      - REP_USER=rep
      - REP_PASSWORD=123456
    links:
      - master

