version: '3.9'

services:
  envoy:
    image: envoyproxy/envoy:v1.25-latest
    container_name: envoy
    restart: always
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
      - "9901:9901"
