version: '3.9'
services:
  master:
    image: postgres:latest
    container_name: master
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: duytc
    ports:
      - '5432:5432'
    volumes: 
      - ./data-master:/var/lib/postgresql/data
  slave:
    image: postgres:latest
    container_name: slave
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: duytc
    ports:
      - '5433:5432'
    volumes: 
      - ./data-slave:/var/lib/postgresql/data