services:
  postgres:
    image: docker.io/postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: anhduy12
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
