services:
  materialized:
    image: materialize/materialized:latest
    container_name: materialized
    ports:
      - "127.0.0.1:6874:6874"  # Materialize Console (UI)
      - "127.0.0.1:6875:6875"  # SQL
      - "127.0.0.1:6876:6876"
      - "127.0.0.1:6877:6877"
