version: '3.9'
services:
  materialized:
    image: materialize/materialized:latest
    container_name: materialized
    ports:
      - '6875:6875'
    volumes: 
    - ./data-materialized:/var/lib/postgresql/data
    environment:
          MZ_LOG: info
  # cli:
  #   image: materialize/cli:latest

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: duytc
    ports:
      - '5432:5432'
    volumes: 
      - ./data-postgres:/var/lib/postgresql/data

  