# ---- Debezium source connector (ví dụ Postgres) ----
debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector

debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=duytc
debezium.source.database.password=anhduy12
debezium.source.database.dbname=appdb

# Server identity
debezium.source.topic.prefix=cdc

# Optional: chỉ capture schema/table cần thiết
debezium.source.schema.include.list=public
debezium.source.table.include.list=public.demo1,public.demo2

# Snapshot
debezium.source.snapshot.mode=initial   # initial / never / schema_only / ...
debezium.source.plugin.name=pgoutput

# ---- Sink: Kafka (Redpanda) ----
debezium.sink.type=kafka
debezium.sink.kafka.bootstrap.servers=redpanda:9092

# Topic naming
debezium.sink.kafka.topic.prefix=cdc

# Serialization: JSON (default)
debezium.format.value=json
debezium.format.key=json

# Nếu muốn unwrap để payload "after" gọn hơn (khuyên dùng):
debezium.transforms=unwrap
debezium.transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
debezium.transforms.unwrap.drop.tombstones=true
debezium.transforms.unwrap.delete.handling.mode=rewrite

